//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        public string No { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string ID_No { get; set; }
        public Nullable<bool> Updated { get; set; }
        public string Class { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Bank { get; set; }
        public string Bank_Account { get; set; }
        public Nullable<double> Acreage { get; set; }
        public string Section { get; set; }
        public string Unit { get; set; }
        public byte[] Photo { get; set; }
        public long Entry { get; set; }
        public Nullable<bool> New { get; set; }
        public string E_Mail { get; set; }
        public Nullable<int> Marital_Status { get; set; }
        public Nullable<int> Account_Types { get; set; }
        public Nullable<double> Serviced_Acres { get; set; }
        public string Customer_Posting_Group { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
