//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Reversal
    {
        public int Entry { get; set; }
        public string Reversal_Id { get; set; }
        public Nullable<int> Entry_Type { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> Posted { get; set; }
        public Nullable<System.DateTime> Datetime_Posted { get; set; }
        public string Reversed_By { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Location { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Reversed { get; set; }
        public Nullable<bool> Sent { get; set; }
        public Nullable<bool> Reverse_document { get; set; }
        public string Reference { get; set; }
        public string Item { get; set; }
        public string Variant { get; set; }
    }
}
