//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string Com_Port { get; set; }
        public Nullable<int> BaudRate { get; set; }
        public Nullable<int> Coffe_type { get; set; }
        public string Branch { get; set; }
        public string Sales_receipt_Printer { get; set; }
        public string Server_url { get; set; }
        public string Factory { get; set; }
        public string Current_crop { get; set; }
        public Nullable<bool> Pick_factory_farmers { get; set; }
        public Nullable<double> Bag_weight { get; set; }
        public Nullable<int> receive_copies { get; set; }
        public string Motto { get; set; }
        public string Email { get; set; }
        public Nullable<int> No_of_sales_per_day { get; set; }
        public Nullable<bool> Allow_Multiple_sales { get; set; }
        public string POS_Outlet { get; set; }
        public Nullable<int> Transfer_copies { get; set; }
        public Nullable<int> Convert_copies { get; set; }
        public string Printer { get; set; }
        public Nullable<int> Stores_receipts_copies { get; set; }
        public Nullable<bool> Load_item_with_stock { get; set; }
        public Nullable<int> Inputs_Receipts { get; set; }
        public Nullable<double> Max_moisture { get; set; }
        public Nullable<double> Max_Recovery { get; set; }
        public Nullable<double> Bags_Weight { get; set; }
        public Nullable<bool> Validate_weight { get; set; }
        public Nullable<bool> Override_Settings { get; set; }
        public Nullable<bool> Scale_Autoconnect { get; set; }
        public Nullable<int> Stock_Calculation { get; set; }
    }
}
