//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rice
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Password_Changed { get; set; }
        public Nullable<System.DateTime> Date_Password_Changed { get; set; }
        public Nullable<bool> Updated { get; set; }
        public string Outlet { get; set; }
        public string Phone { get; set; }
        public string Full_Name { get; set; }
        public Nullable<int> Inputs_supply_note_copies { get; set; }
    }
}
