//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public string Code { get; set; }
        public string Item_Code { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
