//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_Ussd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Menu
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Client { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Menu_Id { get; set; }
    }
}
