//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_Ussd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileEntities : DbContext
    {
        public MobileEntities()
            : base("name=MobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BulkSm> BulkSms { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ussd> Ussds { get; set; }
        public virtual DbSet<Ussd_Language> Ussd_Languages { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<session_variable> session_variables { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Client_Menu> Client_Menus { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Utility> Utilities { get; set; }
    }
}
