//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_Ussd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string Account_No { get; set; }
        public string Account_Name { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<System.DateTime> Transaction_Time { get; set; }
        public Nullable<int> Transaction_Type { get; set; }
        public string MSISDN { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<System.DateTime> Date_Posted { get; set; }
        public string Account_2 { get; set; }
        public string Loan { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string Description { get; set; }
        public Nullable<int> Recover_Loan_From { get; set; }
        public int Entry { get; set; }
        public Nullable<int> Advance_Type { get; set; }
        public string Client { get; set; }
        public string ID_No { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> Min_size { get; set; }
        public string Send_to { get; set; }
        public string Deposit_type { get; set; }
        public string Member_No { get; set; }
        public string Document_No { get; set; }
        public Nullable<double> Eligibility { get; set; }
        public string Conversation_ID { get; set; }
        public Nullable<int> Mpesa_Status { get; set; }
    }
}
