using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;

namespace Weigh
{
    public partial class Allcollections : Form
    {
        public Allcollections()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            try
            {
                Weigh.AutoweighEntities dbContext = new Weigh.AutoweighEntities();
                // Call the Load method to get the data for the given DbSet from the database.
                dbContext.Daily_Collections_Details.Load();
                // This line of code is generated by Data Source Configuration Wizard
                daily_Collections_DetailsBindingSource.DataSource = dbContext.Daily_Collections_Details.Local.ToBindingList();
            }catch(Exception ex)
            { MessageBox.Show(ex.Message); }
        }
    }
}
