using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;

namespace Weigh
{
    public partial class Farmers : Form
    {
        AutoweighEntities Db = new AutoweighEntities();
        public Farmers()
        {

            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
              
            // Call the Load method to get the data for the given DbSet from the database.
            Db.Farmers.Load();
            // This line of code is generated by Data Source Configuration Wizard
            farmerBindingSource.DataSource = Db.Farmers.Local.ToBindingList();
            bindingNavigator1.BindingSource = farmerBindingSource;
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void saveToolStripButton_Click(object sender, EventArgs e)
        {
            try
            {
                Db.SaveChanges();
                MessageBox.Show("Saved successfully");
            }
            catch (Exception ex)
            {
                MessageBox.Show("Unable to save, check if the member no exists");
            }
        }

        private void Farmers_Load(object sender, EventArgs e)
        {

        }

        private void Farmers_FormClosing(object sender, FormClosingEventArgs e)
        {
            try
            {
                if (Db.ChangeTracker.Entries().Any(ee => ee.State == EntityState.Added
                                                        || ee.State == EntityState.Modified
                                                        || ee.State == EntityState.Deleted))
                {
                    DialogResult result1 = MessageBox.Show("There are changes made to your data, do you want to save them?", "Save Changes", MessageBoxButtons.YesNo);
                    if (result1 == DialogResult.Yes)
                        Db.SaveChanges();
                }
            }
            catch (Exception ex) {
            
            }
        }

        private void bindingNavigatorDeleteItem_Click(object sender, EventArgs e)
        {
          
        }

        private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
        {

        }

        private void gridView1_ShowingEditor(object sender, CancelEventArgs e)
        {
            DevExpress.XtraGrid.Views.Grid.GridView view = sender as DevExpress.XtraGrid.Views.Grid.GridView;


            var dd = gridView1.GetRowCellValue(view.FocusedRowHandle, colCum_Cherry);

            if (dd == null)
                gridView1.SetRowCellValue(view.FocusedRowHandle, colCum_Cherry, 0);
            var sd = gridView1.GetRowCellValue(view.FocusedRowHandle, colCum_Mbuni);
            if (sd == null)
                gridView1.SetRowCellValue(view.FocusedRowHandle, colCum_Mbuni, 0);
        }
    }
}
