//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public string User_Type { get; set; }
        public Nullable<bool> Home { get; set; }
        public int Entry { get; set; }
    }
}
