//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Entry { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Changed { get; set; }
        public string Date_Changed { get; set; }
        public string Client { get; set; }
        public string User_Type { get; set; }
        public string UserName { get; set; }
    }
}
