<?xml version="1.0" encoding="utf-8"?><Database Name="Mobile" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\;Initial Catalog=Mobile;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MobileConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Client Code]" Member="Client_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Client Name]" Member="Client_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.groups" Member="groups">
    <Type Name="group">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Contact Groups]" Member="Contact_Groups">
    <Type Name="Contact_Group">
      <Column Name="Entry" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="[Contact Id]" Member="Contact_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Group Id]" Member="Group_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Entry" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Changed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Date Changed]" Member="Date_Changed" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Client" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[User Type]" Member="User_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Languages" Member="Languages">
    <Type Name="Language">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Language Code]" Member="Language_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Language Name]" Member="Language_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.contacts" Member="contacts">
    <Type Name="contact">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contact" Member="contact1" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="client" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Group]" Member="Group" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BulkHeader" Member="BulkHeaders">
    <Type Name="BulkHeader">
      <Column Name="Entry" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Send To]" Member="Send_To" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Created By]" Member="Created_By" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Date Sent]" Member="Date_Sent" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[Sent By]" Member="Sent_By" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Time Sent]" Member="Time_Sent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Client" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Group]" Member="Group" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organizations" Member="Organizations">
    <Type Name="Organization">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Organization Name]" Member="Organization_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Sub County]" Member="Sub_County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubCounties" Member="SubCounties">
    <Type Name="SubCounty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="subcounties" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Counties" Member="Counties">
    <Type Name="County">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="County" Member="County1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Incoming" Member="Incomings">
    <Type Name="Incoming">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Link Id]" Member="Link_Id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Correlator" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[To]" Member="To" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Needs Response]" Member="Needs_Response" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Response" Member="Responses">
    <Type Name="Response">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reply" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Created By]" Member="Created_By" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Language code]" Member="Language_code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Default Language]" Member="Default_Language" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AutoResponse" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="[No Response Alerts]" Member="No_Response_Alerts" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="[alert message]" Member="alert_message" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>