//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileEntities : DbContext
    {
        public MobileEntities()
            : base("name=MobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BulkSm> BulkSms { get; set; }
        public DbSet<Aspirant> Aspirants { get; set; }
        public DbSet<constituency> constituencies { get; set; }
        public DbSet<poll> polls { get; set; }
        public DbSet<session_variable> session_variables { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<Ussd_Language> Ussd_Languages { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<User_Option> User_Options { get; set; }
        public DbSet<Ussd> Ussds { get; set; }
    }
}
