//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Client.AccountTypes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Account_Types_Binding", Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public partial class Account_Types_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Account_Types_Service() {
            this.Url = global::Client.Properties.Settings.Default.Client_AccountTypes_Account_Types_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Account_Types")]
        public Account_Types Read(string Code) {
            object[] results = this.Invoke("Read", new object[] {
                        Code});
            return ((Account_Types)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Code) {
            this.ReadAsync(Code, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Code, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Code}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Account_Types")]
        public Account_Types ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((Account_Types)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Account_Types[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] Account_Types_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((Account_Types[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(Account_Types_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(Account_Types_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref Account_Types Account_Types) {
            object[] results = this.Invoke("Create", new object[] {
                        Account_Types});
            Account_Types = ((Account_Types)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(Account_Types Account_Types) {
            this.CreateAsync(Account_Types, null);
        }
        
        /// <remarks/>
        public void CreateAsync(Account_Types Account_Types, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        Account_Types}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref Account_Types[] Account_Types_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        Account_Types_List});
            Account_Types_List = ((Account_Types[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(Account_Types[] Account_Types_List) {
            this.CreateMultipleAsync(Account_Types_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(Account_Types[] Account_Types_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        Account_Types_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref Account_Types Account_Types) {
            object[] results = this.Invoke("Update", new object[] {
                        Account_Types});
            Account_Types = ((Account_Types)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(Account_Types Account_Types) {
            this.UpdateAsync(Account_Types, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(Account_Types Account_Types, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        Account_Types}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref Account_Types[] Account_Types_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        Account_Types_List});
            Account_Types_List = ((Account_Types[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(Account_Types[] Account_Types_List) {
            this.UpdateMultipleAsync(Account_Types_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(Account_Types[] Account_Types_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        Account_Types_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/account_types:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/account_types", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/account_types", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public partial class Account_Types {
        
        private string keyField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string posting_GroupField;
        
        private decimal minimu_BalanceField;
        
        private bool minimu_BalanceFieldSpecified;
        
        private bool aTM_AllowedField;
        
        private bool aTM_AllowedFieldSpecified;
        
        private bool mobile_Banking_AllowedField;
        
        private bool mobile_Banking_AllowedFieldSpecified;
        
        private bool internet_Banking_AllowedField;
        
        private bool internet_Banking_AllowedFieldSpecified;
        
        private bool earns_InterestField;
        
        private bool earns_InterestFieldSpecified;
        
        private decimal interst_RateField;
        
        private bool interst_RateFieldSpecified;
        
        private Interest_Posting_Date interest_Posting_DateField;
        
        private bool interest_Posting_DateFieldSpecified;
        
        private bool attracts_Ledger_FeeField;
        
        private bool attracts_Ledger_FeeFieldSpecified;
        
        private Ledger_Fee_Type ledger_Fee_TypeField;
        
        private bool ledger_Fee_TypeFieldSpecified;
        
        private decimal ledger_Fee_AmountField;
        
        private bool ledger_Fee_AmountFieldSpecified;
        
        private Ledger_Fee_Posting_Date ledger_Fee_Posting_DateField;
        
        private bool ledger_Fee_Posting_DateFieldSpecified;
        
        private Interest_Calculation_Type interest_Calculation_TypeField;
        
        private bool interest_Calculation_TypeFieldSpecified;
        
        private bool fixed_DepositField;
        
        private bool fixed_DepositFieldSpecified;
        
        private string interest_Expense_AccountField;
        
        private string interest_Payable_AccountField;
        
        private bool cheque_Deposit_AllowedField;
        
        private bool cheque_Deposit_AllowedFieldSpecified;
        
        private bool cash_Deposit_AllowedField;
        
        private bool cash_Deposit_AllowedFieldSpecified;
        
        private bool cash_Withdrawal_AllowedField;
        
        private bool cash_Withdrawal_AllowedFieldSpecified;
        
        private bool cash_Transfer_AllowedField;
        
        private bool cash_Transfer_AllowedFieldSpecified;
        
        private bool payout_AllowedField;
        
        private bool payout_AllowedFieldSpecified;
        
        private bool w_T_Charge_ExemptedField;
        
        private bool w_T_Charge_ExemptedFieldSpecified;
        
        private bool accounts_ValidatedField;
        
        private bool accounts_ValidatedFieldSpecified;
        
        private decimal total_Balance_LCYField;
        
        private bool total_Balance_LCYFieldSpecified;
        
        private Account_Class account_ClassField;
        
        private bool account_ClassFieldSpecified;
        
        private bool group_AccountField;
        
        private bool group_AccountFieldSpecified;
        
        private decimal minimum_Group_MembersField;
        
        private bool minimum_Group_MembersFieldSpecified;
        
        private int accountsField;
        
        private bool accountsFieldSpecified;
        
        private string no_SeriesField;
        
        private string prefixField;
        
        private bool nWD_AccountField;
        
        private bool nWD_AccountFieldSpecified;
        
        private bool share_CapitalField;
        
        private bool share_CapitalFieldSpecified;
        
        private decimal loan_MultiplierField;
        
        private bool loan_MultiplierFieldSpecified;
        
        private bool savings_AccountField;
        
        private bool savings_AccountFieldSpecified;
        
        private decimal recoop_Interest_PercentField;
        
        private bool recoop_Interest_PercentFieldSpecified;
        
        private string reccop_Interest_AccountField;
        
        private bool earns_DividendField;
        
        private bool earns_DividendFieldSpecified;
        
        private Account_Category account_CategoryField;
        
        private bool account_CategoryFieldSpecified;
        
        private int max_WithdrawalsField;
        
        private bool max_WithdrawalsFieldSpecified;
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Posting_Group {
            get {
                return this.posting_GroupField;
            }
            set {
                this.posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public decimal Minimu_Balance {
            get {
                return this.minimu_BalanceField;
            }
            set {
                this.minimu_BalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Minimu_BalanceSpecified {
            get {
                return this.minimu_BalanceFieldSpecified;
            }
            set {
                this.minimu_BalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ATM_Allowed {
            get {
                return this.aTM_AllowedField;
            }
            set {
                this.aTM_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ATM_AllowedSpecified {
            get {
                return this.aTM_AllowedFieldSpecified;
            }
            set {
                this.aTM_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Mobile_Banking_Allowed {
            get {
                return this.mobile_Banking_AllowedField;
            }
            set {
                this.mobile_Banking_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Mobile_Banking_AllowedSpecified {
            get {
                return this.mobile_Banking_AllowedFieldSpecified;
            }
            set {
                this.mobile_Banking_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Internet_Banking_Allowed {
            get {
                return this.internet_Banking_AllowedField;
            }
            set {
                this.internet_Banking_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Internet_Banking_AllowedSpecified {
            get {
                return this.internet_Banking_AllowedFieldSpecified;
            }
            set {
                this.internet_Banking_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Earns_Interest {
            get {
                return this.earns_InterestField;
            }
            set {
                this.earns_InterestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Earns_InterestSpecified {
            get {
                return this.earns_InterestFieldSpecified;
            }
            set {
                this.earns_InterestFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Interst_Rate {
            get {
                return this.interst_RateField;
            }
            set {
                this.interst_RateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Interst_RateSpecified {
            get {
                return this.interst_RateFieldSpecified;
            }
            set {
                this.interst_RateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Interest_Posting_Date Interest_Posting_Date {
            get {
                return this.interest_Posting_DateField;
            }
            set {
                this.interest_Posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Interest_Posting_DateSpecified {
            get {
                return this.interest_Posting_DateFieldSpecified;
            }
            set {
                this.interest_Posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Attracts_Ledger_Fee {
            get {
                return this.attracts_Ledger_FeeField;
            }
            set {
                this.attracts_Ledger_FeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Attracts_Ledger_FeeSpecified {
            get {
                return this.attracts_Ledger_FeeFieldSpecified;
            }
            set {
                this.attracts_Ledger_FeeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Ledger_Fee_Type Ledger_Fee_Type {
            get {
                return this.ledger_Fee_TypeField;
            }
            set {
                this.ledger_Fee_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Ledger_Fee_TypeSpecified {
            get {
                return this.ledger_Fee_TypeFieldSpecified;
            }
            set {
                this.ledger_Fee_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Ledger_Fee_Amount {
            get {
                return this.ledger_Fee_AmountField;
            }
            set {
                this.ledger_Fee_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Ledger_Fee_AmountSpecified {
            get {
                return this.ledger_Fee_AmountFieldSpecified;
            }
            set {
                this.ledger_Fee_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Ledger_Fee_Posting_Date Ledger_Fee_Posting_Date {
            get {
                return this.ledger_Fee_Posting_DateField;
            }
            set {
                this.ledger_Fee_Posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Ledger_Fee_Posting_DateSpecified {
            get {
                return this.ledger_Fee_Posting_DateFieldSpecified;
            }
            set {
                this.ledger_Fee_Posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Interest_Calculation_Type Interest_Calculation_Type {
            get {
                return this.interest_Calculation_TypeField;
            }
            set {
                this.interest_Calculation_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Interest_Calculation_TypeSpecified {
            get {
                return this.interest_Calculation_TypeFieldSpecified;
            }
            set {
                this.interest_Calculation_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Fixed_Deposit {
            get {
                return this.fixed_DepositField;
            }
            set {
                this.fixed_DepositField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fixed_DepositSpecified {
            get {
                return this.fixed_DepositFieldSpecified;
            }
            set {
                this.fixed_DepositFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Interest_Expense_Account {
            get {
                return this.interest_Expense_AccountField;
            }
            set {
                this.interest_Expense_AccountField = value;
            }
        }
        
        /// <remarks/>
        public string Interest_Payable_Account {
            get {
                return this.interest_Payable_AccountField;
            }
            set {
                this.interest_Payable_AccountField = value;
            }
        }
        
        /// <remarks/>
        public bool Cheque_Deposit_Allowed {
            get {
                return this.cheque_Deposit_AllowedField;
            }
            set {
                this.cheque_Deposit_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cheque_Deposit_AllowedSpecified {
            get {
                return this.cheque_Deposit_AllowedFieldSpecified;
            }
            set {
                this.cheque_Deposit_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Cash_Deposit_Allowed {
            get {
                return this.cash_Deposit_AllowedField;
            }
            set {
                this.cash_Deposit_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cash_Deposit_AllowedSpecified {
            get {
                return this.cash_Deposit_AllowedFieldSpecified;
            }
            set {
                this.cash_Deposit_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Cash_Withdrawal_Allowed {
            get {
                return this.cash_Withdrawal_AllowedField;
            }
            set {
                this.cash_Withdrawal_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cash_Withdrawal_AllowedSpecified {
            get {
                return this.cash_Withdrawal_AllowedFieldSpecified;
            }
            set {
                this.cash_Withdrawal_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Cash_Transfer_Allowed {
            get {
                return this.cash_Transfer_AllowedField;
            }
            set {
                this.cash_Transfer_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cash_Transfer_AllowedSpecified {
            get {
                return this.cash_Transfer_AllowedFieldSpecified;
            }
            set {
                this.cash_Transfer_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Payout_Allowed {
            get {
                return this.payout_AllowedField;
            }
            set {
                this.payout_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Payout_AllowedSpecified {
            get {
                return this.payout_AllowedFieldSpecified;
            }
            set {
                this.payout_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool W_T_Charge_Exempted {
            get {
                return this.w_T_Charge_ExemptedField;
            }
            set {
                this.w_T_Charge_ExemptedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool W_T_Charge_ExemptedSpecified {
            get {
                return this.w_T_Charge_ExemptedFieldSpecified;
            }
            set {
                this.w_T_Charge_ExemptedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Accounts_Validated {
            get {
                return this.accounts_ValidatedField;
            }
            set {
                this.accounts_ValidatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Accounts_ValidatedSpecified {
            get {
                return this.accounts_ValidatedFieldSpecified;
            }
            set {
                this.accounts_ValidatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Total_Balance_LCY {
            get {
                return this.total_Balance_LCYField;
            }
            set {
                this.total_Balance_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_Balance_LCYSpecified {
            get {
                return this.total_Balance_LCYFieldSpecified;
            }
            set {
                this.total_Balance_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Account_Class Account_Class {
            get {
                return this.account_ClassField;
            }
            set {
                this.account_ClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Account_ClassSpecified {
            get {
                return this.account_ClassFieldSpecified;
            }
            set {
                this.account_ClassFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Group_Account {
            get {
                return this.group_AccountField;
            }
            set {
                this.group_AccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Group_AccountSpecified {
            get {
                return this.group_AccountFieldSpecified;
            }
            set {
                this.group_AccountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Minimum_Group_Members {
            get {
                return this.minimum_Group_MembersField;
            }
            set {
                this.minimum_Group_MembersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Minimum_Group_MembersSpecified {
            get {
                return this.minimum_Group_MembersFieldSpecified;
            }
            set {
                this.minimum_Group_MembersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Accounts {
            get {
                return this.accountsField;
            }
            set {
                this.accountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountsSpecified {
            get {
                return this.accountsFieldSpecified;
            }
            set {
                this.accountsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string No_Series {
            get {
                return this.no_SeriesField;
            }
            set {
                this.no_SeriesField = value;
            }
        }
        
        /// <remarks/>
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public bool NWD_Account {
            get {
                return this.nWD_AccountField;
            }
            set {
                this.nWD_AccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NWD_AccountSpecified {
            get {
                return this.nWD_AccountFieldSpecified;
            }
            set {
                this.nWD_AccountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Share_Capital {
            get {
                return this.share_CapitalField;
            }
            set {
                this.share_CapitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Share_CapitalSpecified {
            get {
                return this.share_CapitalFieldSpecified;
            }
            set {
                this.share_CapitalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Loan_Multiplier {
            get {
                return this.loan_MultiplierField;
            }
            set {
                this.loan_MultiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Loan_MultiplierSpecified {
            get {
                return this.loan_MultiplierFieldSpecified;
            }
            set {
                this.loan_MultiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Savings_Account {
            get {
                return this.savings_AccountField;
            }
            set {
                this.savings_AccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Savings_AccountSpecified {
            get {
                return this.savings_AccountFieldSpecified;
            }
            set {
                this.savings_AccountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Recoop_Interest_Percent {
            get {
                return this.recoop_Interest_PercentField;
            }
            set {
                this.recoop_Interest_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Recoop_Interest_PercentSpecified {
            get {
                return this.recoop_Interest_PercentFieldSpecified;
            }
            set {
                this.recoop_Interest_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Reccop_Interest_Account {
            get {
                return this.reccop_Interest_AccountField;
            }
            set {
                this.reccop_Interest_AccountField = value;
            }
        }
        
        /// <remarks/>
        public bool Earns_Dividend {
            get {
                return this.earns_DividendField;
            }
            set {
                this.earns_DividendField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Earns_DividendSpecified {
            get {
                return this.earns_DividendFieldSpecified;
            }
            set {
                this.earns_DividendFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Account_Category Account_Category {
            get {
                return this.account_CategoryField;
            }
            set {
                this.account_CategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Account_CategorySpecified {
            get {
                return this.account_CategoryFieldSpecified;
            }
            set {
                this.account_CategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Max_Withdrawals {
            get {
                return this.max_WithdrawalsField;
            }
            set {
                this.max_WithdrawalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Max_WithdrawalsSpecified {
            get {
                return this.max_WithdrawalsFieldSpecified;
            }
            set {
                this.max_WithdrawalsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MandatorySpecified {
            get {
                return this.mandatoryFieldSpecified;
            }
            set {
                this.mandatoryFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public enum Interest_Posting_Date {
        
        /// <remarks/>
        Last_Period_Day,
        
        /// <remarks/>
        Current_Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public enum Ledger_Fee_Type {
        
        /// <remarks/>
        Monthly,
        
        /// <remarks/>
        Annual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public enum Ledger_Fee_Posting_Date {
        
        /// <remarks/>
        Last_Period_Day,
        
        /// <remarks/>
        Current_Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public enum Interest_Calculation_Type {
        
        /// <remarks/>
        Monthly,
        
        /// <remarks/>
        Annual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public enum Account_Class {
        
        /// <remarks/>
        BOSA,
        
        /// <remarks/>
        FOSA,
        
        /// <remarks/>
        Fixed_Deposit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public enum Account_Category {
        
        /// <remarks/>
        General,
        
        /// <remarks/>
        Group_Account,
        
        /// <remarks/>
        Junior_Account,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public partial class Account_Types_Filter {
        
        private Account_Types_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public Account_Types_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/account_types")]
    public enum Account_Types_Fields {
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Posting_Group,
        
        /// <remarks/>
        Minimu_Balance,
        
        /// <remarks/>
        ATM_Allowed,
        
        /// <remarks/>
        Mobile_Banking_Allowed,
        
        /// <remarks/>
        Internet_Banking_Allowed,
        
        /// <remarks/>
        Earns_Interest,
        
        /// <remarks/>
        Interst_Rate,
        
        /// <remarks/>
        Interest_Posting_Date,
        
        /// <remarks/>
        Attracts_Ledger_Fee,
        
        /// <remarks/>
        Ledger_Fee_Type,
        
        /// <remarks/>
        Ledger_Fee_Amount,
        
        /// <remarks/>
        Ledger_Fee_Posting_Date,
        
        /// <remarks/>
        Interest_Calculation_Type,
        
        /// <remarks/>
        Fixed_Deposit,
        
        /// <remarks/>
        Interest_Expense_Account,
        
        /// <remarks/>
        Interest_Payable_Account,
        
        /// <remarks/>
        Cheque_Deposit_Allowed,
        
        /// <remarks/>
        Cash_Deposit_Allowed,
        
        /// <remarks/>
        Cash_Withdrawal_Allowed,
        
        /// <remarks/>
        Cash_Transfer_Allowed,
        
        /// <remarks/>
        Payout_Allowed,
        
        /// <remarks/>
        W_T_Charge_Exempted,
        
        /// <remarks/>
        Accounts_Validated,
        
        /// <remarks/>
        Total_Balance_LCY,
        
        /// <remarks/>
        Account_Class,
        
        /// <remarks/>
        Group_Account,
        
        /// <remarks/>
        Minimum_Group_Members,
        
        /// <remarks/>
        Accounts,
        
        /// <remarks/>
        No_Series,
        
        /// <remarks/>
        Prefix,
        
        /// <remarks/>
        NWD_Account,
        
        /// <remarks/>
        Share_Capital,
        
        /// <remarks/>
        Loan_Multiplier,
        
        /// <remarks/>
        Savings_Account,
        
        /// <remarks/>
        Recoop_Interest_Percent,
        
        /// <remarks/>
        Reccop_Interest_Account,
        
        /// <remarks/>
        Earns_Dividend,
        
        /// <remarks/>
        Account_Category,
        
        /// <remarks/>
        Max_Withdrawals,
        
        /// <remarks/>
        Mandatory,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Account_Types Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Account_Types)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Account_Types Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Account_Types)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Account_Types[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Account_Types[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Account_Types Account_Types {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Account_Types)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Account_Types[] Account_Types_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Account_Types[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Account_Types Account_Types {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Account_Types)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Account_Types[] Account_Types_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Account_Types[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591