using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;

namespace Coffee
{
    public partial class Allcollections : Form
    {   AutoweighEntities db = new AutoweighEntities(coffee.ConnectionString());
        public Allcollections()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            try
            {
             
                ribbonPage1.Text = this.Text;
             
                // Call the Load method to get the data for the given DbSet from the database.
         
                // This line of code is generated by Data Source Configuration Wizard
                daily_Collections_DetailsBindingSource.DataSource = db.Daily_Collections_Details.ToList();
                bindingNavigator1.BindingSource = daily_Collections_DetailsBindingSource;
            }catch(Exception ex)
            { MessageBox.Show(ex.Message); }
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridView1_MouseDown(object sender, MouseEventArgs e)
        {
            if (e.Button == System.Windows.Forms.MouseButtons.Right)
            {              
                cellcontext.Show(gridControl1,e.Location);
            }
        }

        private void cellcontext_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
        {
            switch (e.ClickedItem.Name)
            {
                case "filterWithThisValueToolStripMenuItem":
                    gridView1.ActiveFilterString = "[" + gridView1.FocusedColumn.FieldName + "] = '" + gridView1.FocusedValue + "'";
                    break;
                case "collectEntryToolStripMenuItem":
                    var c = (Daily_Collections_Detail)gridView1.GetFocusedRow();
                    using (var form = new CollectEntries(c))
                    {
                        var d = form.ShowDialog();
                        if (d == System.Windows.Forms.DialogResult.OK)
                        {

                            
                        }

                    }
                    break;
            }
        }

        private void toolStripButton1_Click(object sender, EventArgs e)
        {
            try{
             SaveFileDialog saveFileDialog1 = new SaveFileDialog();
             saveFileDialog1.Filter = "Excel|*.xls|Excel 2010|*.xlsx";
   saveFileDialog1.Title = "Save list to File";  
   saveFileDialog1.ShowDialog();  

   // If the file name is not an empty string open it for saving.  
   if(saveFileDialog1.FileName != "")  
   {
       gridControl1.ExportToXlsx(saveFileDialog1.FileName);
        }}
            catch(Exception ex){Logging.Logging.ReportError(ex);
            MessageBox.Show("Unable to save file");}
        }

        private void ribbonControl1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
                BindingSource b = daily_Collections_DetailsBindingSource;
                    
                switch (e.Item.Name)
                {
                    case "btndaily":
                      
                        break;

                    case "btnrefresh":
                        daily_Collections_DetailsBindingSource.DataSource = db.Daily_Collections_Details.ToList();
                        break;
                    case "navfirst":
                        b.MoveFirst();
                        break;  
                        case "navnext":
                        b.MoveNext();
                            break;
                        case "navprevious":
                            b.MovePrevious();
                            break;
                        case "navlast":
                            b.MoveLast();
                            break;
                        case "actionxlsx":
                            try
                            {
                                SaveFileDialog saveFileDialog1 = new SaveFileDialog();
                                  saveFileDialog1.Filter = "Excel 2010|*.xlsx";
                                saveFileDialog1.Title = "Save list to File";
                                saveFileDialog1.ShowDialog();

                                // If the file name is not an empty string open it for saving.  
                                if (saveFileDialog1.FileName != "")
                                {
                                    gridControl1.ExportToXlsx(saveFileDialog1.FileName);
                                }
                            }
                            catch (Exception ex)
                            {
                                Logging.Logging.ReportError(ex);
                                MessageBox.Show("Unable to save file");
                            }
                            break;
                    case "actionxls":
                            try
                            {
                                SaveFileDialog saveFileDialog1 = new SaveFileDialog();
                               saveFileDialog1.Filter = "Excel File|*.xls"; 
                                saveFileDialog1.Title = "Save list to File";
                                saveFileDialog1.ShowDialog();

                                // If the file name is not an empty string open it for saving.  
                                if (saveFileDialog1.FileName != "")
                                {
                                    gridControl1.ExportToXls(saveFileDialog1.FileName);
                                }
                            }
                            catch (Exception ex)
                            {
                                Logging.Logging.ReportError(ex);
                                MessageBox.Show("Unable to save file");
                            }
                            break;   
                    case "actionpdf":
                            try
                            {
                                SaveFileDialog saveFileDialog1 = new SaveFileDialog();
                                saveFileDialog1.Filter = "Pdf|*.pdf";
                                saveFileDialog1.Title = "Save list to File";
                                saveFileDialog1.ShowDialog();

                                // If the file name is not an empty string open it for saving.  
                                if (saveFileDialog1.FileName != "")
                                {
                                    gridControl1.ExportToPdf(saveFileDialog1.FileName);
                                }
                            }
                            catch (Exception ex)
                            {
                                Logging.Logging.ReportError(ex);
                                MessageBox.Show("Unable to save file");
                            }
                            break;
                }
        }

        private void daily_Collections_DetailsBindingSource_CurrentChanged(object sender, EventArgs e)
        {
            if (daily_Collections_DetailsBindingSource.Current == null)
                disable();
            else
                enable();

            if (daily_Collections_DetailsBindingSource.Position == 0)
            {
                navprevious.Enabled = false;
                navfirst.Enabled = false;
            }
            else
            {
                navprevious.Enabled = true;
                navfirst.Enabled = true;
            }

            if (daily_Collections_DetailsBindingSource.Position == daily_Collections_DetailsBindingSource.Count - 1)
            {
                navnext.Enabled = false;
                navlast.Enabled = false;
            }
            else
            {
                navnext.Enabled = true;
                navlast.Enabled = true;
            }
        }

        private void enable() {
            navlast.Enabled = true;
            navprevious.Enabled = true; 
            navnext.Enabled = true;
            navfirst.Enabled = true;
           
        }  
        private void disable() {
            navlast.Enabled = false;
            navprevious.Enabled = false;
            navfirst.Enabled = false;
            navnext.Enabled = false;
        }

        private void Allcollections_Load(object sender, EventArgs e)
        {

        }

        private void collectEntryToolStripMenuItem_Click(object sender, EventArgs e)
        {

        }

        private void btndaily_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void btndaily_EditValueChanged(object sender, EventArgs e)
        {
            if (btndaily.EditValue != null)
            {
                gridView1.ActiveFilterString = string.Format("[{0}] = '{1}'", colCollections_Date.FieldName, btndaily.EditValue);

            }
        }
    }
}
