//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string No { get; set; }
        public string Description { get; set; }
        public string Base_Unit_of_Measure { get; set; }
        public Nullable<double> Last_Direct_Cost { get; set; }
    }
}
