//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Setup
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Block_No { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Startat { get; set; }
        public Nullable<bool> Connected { get; set; }
        public Nullable<System.DateTime> Last_Connected { get; set; }
        public Nullable<int> Fetch_interval_ms { get; set; }
        public string Address { get; set; }
        public Nullable<int> Rack { get; set; }
        public Nullable<int> Slot { get; set; }
    }
}
